# Generated by Django 3.1.4 on 2021-01-10 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0002_auto_20210110_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Date',
            new_name='Current',
        ),
        migrations.AlterModelOptions(
            name='current',
            options={'ordering': ['day']},
        ),
        migrations.RenameField(
            model_name='current',
            old_name='date',
            new_name='day',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='dates',
        ),
        migrations.AddField(
            model_name='flight',
            name='when',
            field=models.ManyToManyField(to='airlines.Current'),
        ),
    ]
