# Generated by Django 3.1.4 on 2021-01-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0004_auto_20210110_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current',
            name='flights',
        ),
        migrations.AddField(
            model_name='flight',
            name='days',
            field=models.ManyToManyField(blank=True, to='airlines.Current'),
        ),
    ]
