# Generated by Django 3.1.4 on 2021-01-10 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0005_auto_20210110_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='time',
            new_name='arrival_time',
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
    ]
