# Generated by Django 3.1.4 on 2021-01-24 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0008_auto_20210124_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='days',
        ),
        migrations.CreateModel(
            name='Single',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='airlines.current')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airlines.flight')),
            ],
        ),
    ]
