# Generated by Django 3.1.4 on 2021-01-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0011_flight_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(default=130),
        ),
    ]
