# Generated by Django 3.1.4 on 2021-01-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0012_flight_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('transit', models.BooleanField(default=False)),
                ('day', models.DateTimeField(auto_now_add=True)),
                ('flight1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='airlines.single')),
                ('flight2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_transit', to='airlines.single')),
                ('passenger', models.ManyToManyField(to='airlines.Passenger')),
            ],
        ),
    ]
