# Generated by Django 3.1.4 on 2021-02-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0014_auto_20210201_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='passenger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airlines.passenger'),
        ),
    ]
