# Generated by Django 3.1.4 on 2021-02-01 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0015_seat_passenger'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
