# Generated by Django 3.1.4 on 2021-02-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0017_auto_20210201_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='passenger',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='airlines.passenger'),
        ),
    ]
