# Generated by Django 3.1.4 on 2021-02-01 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0018_auto_20210201_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='airlines.single'),
        ),
    ]
