# Generated by Django 3.1.4 on 2021-02-01 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0019_seat_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='flight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seat', to='airlines.single'),
        ),
    ]
