# Generated by Django 3.1.4 on 2021-02-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0020_auto_20210201_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(default=132),
        ),
        migrations.AlterField(
            model_name='single',
            name='capacity',
            field=models.IntegerField(default=132),
        ),
    ]
