# Generated by Django 3.1.4 on 2021-02-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0022_auto_20210204_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flight',
            name='days',
            field=models.ManyToManyField(to='airlines.Current'),
        ),
    ]
