# Generated by Django 3.1.4 on 2021-02-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0023_auto_20210204_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='days',
            field=models.ManyToManyField(blank=True, to='airlines.Current'),
        ),
    ]
