# Generated by Django 3.1.4 on 2021-02-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0024_auto_20210204_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='passengers_with_baggage',
            field=models.ManyToManyField(related_name='baggage', to='airlines.Passenger'),
        ),
    ]
