# Generated by Django 3.1.4 on 2021-02-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airlines', '0025_booking_passengers_with_baggage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.URLField(),
        ),
    ]
